name: voyagair
description: VoyagAir is a bus ticket booking app that allows users to book bus tickets online. It is a complete solution for bus booking and ticketing.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Base
  cupertino_icons: ^1.0.6
  nb_utils: ^6.0.4
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0
  # STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.0.1
  # QI Bus
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.11.0

dependency_overrides:
  http: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - images/qibus/
    - images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700